query GetDatasetsByPlatform($platform: String!, $start: Int!, $count: Int!) {
  search(
    input: {
      type: DATASET,
      query: $platform,
      start: $start,
      count: $count
    }
  ) {
    searchResults {
      entity {
        urn
      }
    }
  }
}


### variables
  "platform": "XXX",
  "start": 0,
  "count": 1000
}
###